routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('/');
Route::get('/', 'PageController@home')->name('home');

Route::name('pages.')->group(function () {

    Route::get('/actions', 'PageController@actions')->name('actions');
    Route::get('/photo-gallery', 'PageController@static')->name('gallery');
    Route::get('/contacts', 'PageController@contacts')->name('contacts');

    Route::get('/about', 'PageController@static')->name('about');
    Route::get('/services', 'PageController@static')->name('services');
    Route::get('/pay-delivery', 'PageController@static')->name('pay-delivery');

    Route::get('/page/{static}', 'PageController@static')->name('static');

    Route::get('/search', 'PageController@search')->name('search');
});

Route::prefix('/question')->name('question.')->group(function () {
    Route::get('/', 'QuestionController@show')->name('show');
    Route::post('/send', 'QuestionController@send')->name('send');
});

Route::name('articles.')->group(function () {
   Route::get('/articles', 'ArticleController@list')->name('list');
   Route::get('/articles/{article}', 'ArticleController@view')->name('view');
});

Route::name('catalog.')->prefix('/catalog')->group(function () {
    Route::get('/{categoriesURI}/product/{product}', 'ProductController@view')
        ->where('categoriesURI', '.+')->where('product', '.+')->name('product');

    Route::get('/{categoriesURI}/{category}', 'ProductCategoryController@subView')
        ->where(['categoriesURI' => '.+', 'category' => '.+'])->name('subcategory');
    Route::get('/{category}', 'ProductCategoryController@view')->where('category', '.+')
        ->name('category');
    Route::get('/', 'ProductCategoryController@catalog')->name('categories');
});

Route::get('/{any}', 'URLsController@index')->where('any', '^(?!admin|sitemap\.xml).*');
Route::get('/sitemap.xml', 'SitemapController@index');

Route::group(['prefix' => 'admin'], function () {
    Route::group(['prefix' => 'products', 'namespace' => 'Admin', 'middleware' => 'admin.user'], function () {
        Route::put('{id}/product-properties/update', 'ProductController@updateProperties')
            ->name('admin.products.product-properties.update');

        Route::get('properties', 'ProductPropertyController@index')->name('admin.products.properties');
        Route::post('properties/store', 'ProductPropertyController@store')->name('admin.products.property.store');
        Route::put('properties/update', 'ProductPropertyController@update')->name('admin.products.property.update');
        Route::delete('properties/delete', 'ProductPropertyController@delete')->name('admin.products.property.delete');

        Route::get('values/{property}', 'ProductPropertyCharController@index')->name('admin.products.property.value.char.names');
        Route::get('values', 'ProductPropertyCharController@all')->name('admin.products.property.value.char.all-names');
        Route::post('value/store', 'ProductPropertyCharController@store')->name('admin.products.property.value.char.name.store');
        Route::put('value/update', 'ProductPropertyCharController@update')->name('admin.products.property.value.char.name.update');
        Route::delete('value/delete', 'ProductPropertyCharController@delete')->name('admin.products.property.value.char.name.delete');
    });

    Route::group(['prefix' => 'categories', 'namespace' => 'Admin', 'middleware' => 'admin.user'], function () {
        Route::put('{id}/product-properties/update', 'ProductCategoryController@updateProductProperties')
            ->name('admin.categories.product-properties.update');
    });

    Voyager::routes();

    Route::resource('photogallery', 'Admin\PhotogalleryController', ['as' => 'admin', 'middleware' => 'admin.user']);
    Route::delete('photogallery/{photogallery}/{id}', 'Admin\PhotogalleryController@destroyItem')->name('admin.photogallery.item.delete');
});


app/Photogallery.php
<?php

namespace App;

use App\Services\PhotogalleryService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

class Photogallery extends Model
{
    static public function getStoragePath()
    {
        return Storage::disk('public')->getAdapter()->getPathPrefix();
    }

    public function getFilePath()
    {
        return 'photogalleries'.DIRECTORY_SEPARATOR.$this->shortcode.DIRECTORY_SEPARATOR;
    }

    static public function makeNewFileName($name)
    {
        return base64_encode(request()->file($name)->getClientOriginalName()) .'-'.
            pathinfo(request()->file($name)->getClientOriginalName(), PATHINFO_FILENAME) .'.'.
            request()->file($name)->extension();
    }

    public function save_changes(Request $request, Photogallery $photogalery) {
        $photogalleryService = new PhotogalleryService($photogalery);

        $exist_images = $photogalery->images;
        $exist_alts = $photogalery->alts;
        $exist_titles = $photogalery->titles;
        $exist_display = $photogalery->display_as;
        $fields_for_sub_product = $photogalery->fields_for_subproduct;

        $flag_file_changed = false;

        // update fields
        if( $request->has('gallery_upload_0_alt') ) {
            $i = 0;
            while( $request->has('gallery_upload_'.$i.'_alt') ) {

                $exist_images[$i] = $request->get('gallery_upload_'.$i.'_old_img');
                $exist_alts[$i] = $request->get('gallery_upload_'.$i.'_alt');
                $exist_titles[$i] = $request->get('gallery_upload_'.$i.'_title');
                $exist_display[$i] = $request->get('gallery_upload_'.$i.'_display');

                $fields_for_sub_product[$i]['title'] = $request->get('title_for_'.$i.'_sub_0');
                $fields_for_sub_product[$i]['key'] = $request->get('key_for_'.$i.'_sub_0');
                $fields_for_sub_product[$i]['value'] = $request->get('value_for_'.$i.'_sub_0');

                $i++;
            }
        }

        // change gallery slug detected
        extract($photogalleryService->changeSlugIfNeed($exist_images, $flag_file_changed));

        if( $request->files->count() ) {
            foreach($request->files as $name => $file) {
                $itemNum = (integer) str_replace('gallery_upload_', '', $name);

                $request->file($name)->storeAs($this->getFilePath(), $this->makeNewFileName($name));

                $exist_images[$itemNum] = $this->getFilePath().$this->makeNewFileName($name);
            }
            $flag_file_changed = true;
        }

        extract($photogalleryService->deleteIfNeed($exist_images, $exist_alts, $exist_titles, $exist_display, $fields_for_sub_product, $flag_file_changed));

        $photogalery->enabled = $request->get('enable') && $request->get('enable') == 'on' ? true : false;

        // if files changed
        if( $flag_file_changed ){
            $photogalery->images = $exist_images;
            $photogalery->alts = $exist_alts;
            $photogalery->titles = $exist_titles;
            $photogalery->display_as = $exist_display;
            $photogalery->fields_for_subproduct = $fields_for_sub_product;

            $photogalleryService->sortItems();
        }

        $photogalery->save();
    }

    public function add(Request $request) {
        $this->title = $request->get('title');
        $this->shortcode = $request->get('shortcode');

        // upload all files and save alts and titles
        $field_num = 0;
        $files_to_save = array();
        $titles_to_save = array();
        $alts_to_save = array();
        $display = array();
        $fields_for_sub_product = array();

        if( $request->files->count() ) {
            foreach($request->files as $name => $file) {
                $itemNum = (integer) str_replace('gallery_upload_', '', $name);

                $request->file($name)->storeAs($this->getFilePath(), $this->makeNewFileName($name));

//                $files_to_save[$itemNum] = $this->getFilePath().$this->makeNewFileName($name);
                $files_to_save[] = $this->getFilePath().$this->makeNewFileName($name);                

                $titles_to_save[] = $request->get('gallery_upload_'.$field_num.'_title');
                $alts_to_save[] = $request->get('gallery_upload_'.$field_num.'_alt');
                $display[] = $request->get('gallery_upload_'.$field_num.'_display');
                $fields_for_sub_product_new = array();
                $fields_for_sub_product_new['title'] = $request->get('title_for_'.$field_num.'_sub_0');
                $fields_for_sub_product_new['key'] = $request->get('key_for_'.$field_num.'_sub_0');
                $fields_for_sub_product_new['value'] = $request->get('value_for_'.$field_num.'_sub_0');
    
                $fields_for_sub_product[] = $fields_for_sub_product_new;

                $field_num++;
            }
        }

        $this->enabled = $request->get('enable') && $request->get('enable') == 'off' ? true : false;
        $this->images = $files_to_save;
        $this->display_as = $display;
        $this->alts = $alts_to_save;
        $this->titles = $titles_to_save;
        $this->fields_for_subproduct = $fields_for_sub_product;

        $this->save();
    }

    public function del(Photogallery $photogalery) {
        $path_to_dir = $this->getStoragePath().'photogalleries'.DIRECTORY_SEPARATOR.$photogalery->shortcode;
        $deleted_flag = false;
        if( file_exists($path_to_dir) ) {
            $directory_iterator = new \RecursiveDirectoryIterator($path_to_dir, \FilesystemIterator::SKIP_DOTS);
            $directory_iterator->rewind();
            while($directory_iterator->valid()) {
                unlink($path_to_dir.DIRECTORY_SEPARATOR.$directory_iterator->getSubPathName());
                $directory_iterator->next();
            }
            if( rmdir($path_to_dir) ) {
                $photogalery->delete();
                $deleted_flag = true;
            }
        }

        if( !$deleted_flag ) {
            $photogalery->delete();
        }
    }

    /**
     * @param int $deletingItemId
     * @return bool
     */
    public function delItem(int $deletingItemId) {
        Storage::delete($this->images[$deletingItemId]);

        $this->images = array_diff_key($this->images, [$deletingItemId => '']);
        $this->alts = array_diff_key($this->alts, [$deletingItemId => '']);
        $this->titles = array_diff_key($this->titles, [$deletingItemId => '']);
        $this->display_as = array_diff_key($this->display_as, [$deletingItemId => '']);
        $this->fields_for_subproduct = array_diff_key($this->fields_for_subproduct, [$deletingItemId => '']);

        return $this->save();
    }

    public function prepare_to_get(Photogallery $photogalery) {
        $images = array();

        foreach($photogalery->images as $image) {
            $images[] = Storage::disk('public')->url($image);
        }

        $photogalery['images'] = $images;

        return $photogalery;
    }

    public function show(Request $request) {
        $url = parse_url($request->getRequestUri());
        $parsed_url_path = explode('/', trim($url['path'], '/'));
        $photogalery = Photogallery::where('shortcode', array_shift($parsed_url_path))->first();
        if( (bool)$photogalery ) {
            return $this->prepare_to_get($photogalery);
        }
        return null;
    }


    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */

    public function setImagesAttribute($value)
    {
        $this->attributes['images'] = serialize($value);
    }

    public function setAltsAttribute($value)
    {
        $this->attributes['alts'] = serialize($value);
    }

    public function setDisplayAsAttribute($value)
    {
        $this->attributes['display_as'] = serialize($value);
    }

    public function setTitlesAttribute($value)
    {
        $this->attributes['titles'] = serialize($value);
    }

    public function setFieldsForSubproductAttribute($value)
    {
        $this->attributes['fields_for_subproduct'] = serialize($value);
    }


    /*
    |--------------------------------------------------------------------------
    | ACCESORS
    |--------------------------------------------------------------------------
    */

    public function getImagesAttribute($value)
    {
        if( is_array($value) ) {
            return $value;
        }
        return unserialize($value);
    }

    public function getAltsAttribute($value)
    {
        if( is_array($value) ) {
            return $value;
        }
        return unserialize($value);
    }

    public function getDisplayAsAttribute($value)
    {
        if( is_array($value) ) {
            return $value;
        }
        return unserialize($value);
    }

    public function getTitlesAttribute($value)
    {
        if( is_array($value) ) {
            return $value;
        }
        return unserialize($value);
    }

    public function getFieldsForSubproductAttribute($value)
    {
        if( is_array($value) ) {
            return $value;
        }
        return unserialize($value);
    }
}

app/Http/Controllers/Admin/PhotogalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\PhotogalleryDestroyRequest;
use App\Http\Requests\PhotogalleryStoreRequest;
use App\Http\Requests\PhotogalleryUpdateRequest;
use Illuminate\Http\Request;
use \App\Photogallery;

class PhotogalleryController extends Controller
{
    public function index()
    {
        $galleries = Photogallery::all();

        return view('admin.photogallery.index', compact('galleries'));
    }

    public function show(Request $request, Photogallery $photogallery) {
        return redirect(route('admin.photogallery.edit', ['photogallery' => $photogallery->id]));
    }

    public function create()
    {
        return view('admin.photogallery.create');
    }

    public function store(PhotogalleryStoreRequest $request, Photogallery $photogallery)
    {
        $photogallery->add($request);

        return redirect()->route('admin.photogallery.index')
            ->with(
                [
                    'message' => 'Фотогаллерея <a href="'. route('admin.photogallery.edit', $photogallery) .'">'. $photogallery->title.' </a> создана!',
                    'alert-type' => 'success'
                ]
            );
    }

    public function edit(Request $request, Photogallery $photogallery)
    {
        return view('admin.photogallery.edit', ['gallery' => $photogallery]);
    }

    public function update(PhotogalleryUpdateRequest $request, Photogallery $photogallery)
    {
        $photogallery->save_changes($request, $photogallery);

        return redirect()->route('admin.photogallery.index')
            ->with([
                'message' => 'Фотогаллерея <a href="'. route('admin.photogallery.edit', $photogallery) .'">'. $photogallery->title.' </a> обновлена!',
                'alert-type' => 'success'
            ]);
    }

    public function destroy(Photogallery $photogallery) {
        $photogallery->del($photogallery);

        return redirect()->route('admin.photogallery.index')
            ->with(['message' => "Фотогаллерея удалена!", 'alert-type' => 'success']);
    }

    public function destroyItem(Photogallery $photogallery, int $id ) {

        if($photogallery->delItem($id)){
            return response()->json([
                'status' => 'ok',
                'msg' => $id+1 . '-й елемент фотогаллереи удален']
            );
        }

        return response()->json([
            'status' => 'error',
            'msg' => 'Ошибка елемент не был уделен'],
        403);
    }
}

resources/views/admin/photogallery/create.blade.php
@extends('voyager::master')
@section('content')
    <div class="page-content edit-add container-fluid">
        <div class="row">

            <div class="page-content col-sm-12">
                <h1 class="page-title">Добавление новой галереи</h1>
            </div>

            <div class="page-content col-sm-12">
                <form id="store_photogallery" method="post" enctype="multipart/form-data" action="{{ route('admin.photogallery.store') }}" class="container-fluid">
                    @csrf

                    <div class="row">
                        <div class="form-group col-sm-2">
                            <label>
                                <span>Название</span>
                                <input type="text" name="title" required placeholder="Название" class="form-control"/>
                            </label>
                        </div>

                        <div class="form-group col-sm-2">
                            <label>
                                <span>Код для вставки</span>
                                <input type="text" name="shortcode" readonly data-slug-origin="title"
                                       placeholder="Код для вставки" class="form-control"/>
                            </label>
                        </div>

                        <div class="form-group col-sm-2">
                            <label>
                                <input type="checkbox" name="enable" checked="checked" class="toggleswitch"/>
                                <span>Включить</span>
                            </label>
                        </div>
                    </div>

                    <div class="row items-block">
                        @include('admin.photogallery.inc.item', ['i' => '0', 'number' => 1])
                    </div>

                    <div class="row btns-block">
                        <div class="form-group col-sm-12" id="gallery_add_button">
                            <a id="add_new_file_upload_group" class="btn btn-success btn-add-new">+ Добавить поле</a>
                        </div>

                        <div class="form-group col-sm-12" id="gallery_save_button">
                            <button type="submit" form="store_photogallery" class="btn btn-primary">Сохранить</button>
                        </div>
                    </div>
                </form>

                @section('javascript')
                    <script src="{{ asset('js/photogallery.js') }}"></script>

                    <script>
                        var photogallery_data = {
                            itemTemp: function() {
                                return `@include('admin.photogallery.inc.item', [
                                    'i' => '` + photogallery.get.countPhotos() + `',
                                    'image' => null,
                                    'number' => '` + (1+photogallery.get.countPhotos()) + `',
                                    'isNew' => 'data-isNew=true'])`;
                            },
                            photogalleryId: null,
                            isEditing: false,

                            loader: `@include('layouts.inc.loader')`
                        }
                    </script>
                @endsection
            </div>

        </div>
    </div>
@stop

resources/views/admin/photogallery/edit.blade.php
@extends('voyager::master')
@section('content')
    <div class="container-fluid">
        <div class="row">

            <div class="page-content col-sm-12">
                <h1 class="page-title">Редактировать галерею</h1>
            </div>

            <div class="page-content">
                <form method="post" action="{{ route('admin.photogallery.update', ['photogallery' => $gallery->id]) }}" enctype="multipart/form-data" class="container-fluid">
                    @csrf
                    @method('PUT')

                    <div class="row">
                        <div class="form-group col-sm-2">
                            <label>
                                <span>Название</span>
                                <input type="text" name="title" value="{{ $gallery->title }}" required
                                       placeholder="Название" class="form-control"/>
                            </label>
                        </div>

                        <div class="form-group col-md-2">
                            <label>
                                <span>Код для вставки</span>
                                <input type="text" name="shortcode" readonly data-slug-origin="title"
                                       placeholder="Код для вставки" class="form-control"/>
                            </label>
                        </div>

                        <div class="form-group col-md-2">
                            <label>
                                <input type="checkbox" name="enable"
                                       {{ ($gallery->enabled ? 'checked="checked"' : '') }} class="toggleswitch"/>
                                <span>Включить</span>
                            </label>
                        </div>

                        <div>
                            <input type="hidden" name="deleted_images"/>
                        </div>
                    </div>

                    <div class="row items-block">
                        @php $number=1; @endphp
                    @forelse ($gallery['images'] as $key => $image)
                        @include('admin.photogallery.inc.item', ['i' => $key, 'number' => $number])
                        @php $number++ @endphp
                    @empty
                        @include('admin.photogallery.inc.item', ['i' => '0'])
                    @endforelse
                    </div>

                    <div class="form-group" id="gallery_add_button">
                        <a id="add_new_file_upload_group" class="btn btn-success btn-add-new">+ Добавить поле</a>
                    </div>

                    <div class="form-group" id="gallery_save_button">
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </form>

                @section('javascript')
                <script src="{{ asset('js/photogallery.js?v') }}"></script>

                <script>
                    var photogallery_data = {
                        itemTemp: function() {
                            return `@include('admin.photogallery.inc.item', ['i' => '` + photogallery.get.countPhotos() + `', 'image' => null, 'number' => '` + (1+photogallery.get.countPhotos()) + `', 'isNew' => 'data-isNew=true'])`;
                        },
                        photogalleryId: {{ $gallery->id }},
                        delItemLink: '{{ route('admin.photogallery.item.delete', ['photogallery' => $gallery->id,'id' => 'item_id']) }}',

                        shortcode: '{{ $gallery['shortcode'] }}',
                        isEditing: true,
                        msgs: {
                            deleteFail: 'Ошибка удаления'
                        },

                        loader: `@include('layouts.inc.loader')`
                    }
                </script>
            @endsection
            </div>

        </div>
    </div>
@stop

resources/views/admin/photogallery/index.blade.php
@extends('voyager::master')
@section('content')
  <div class="container-fluid">
      <div class="page-content">
        <h1 class="page-title">Галереи</h1>
        <a href="{{ route('admin.photogallery.create') }}" class="btn btn-success btn-add-new">
          <i class="voyager-plus"></i> <span>Добавить галерею</span>
      </a>
      </div>
      <div class="page-content">
        <table class="table">
        <thead>
          <tr>
            <th scope="col">№</th>
            <th scope="col">Название</th>
            <th scope="col">URL</th>
            <th scope="col">Шорткод</th>
            <th scope="col">Доступные действия</th>
          </tr>
        </thead>
        <tbody>
        @forelse ($galleries as $gallery)
        <tr class="product_category">
          <td>{{ $gallery['id'] }}</td>
          <td>{{ $gallery['title'] }}</td>
          <td>{{ $gallery['shortcode'] }}</td>
          <td><input type="text" value="[{{ $gallery['shortcode'] }}]" /></td>
          <td>
            <form id="destroy_photogallery_{{$gallery->id}}" action="{{ route('admin.photogallery.destroy', $gallery['id']) }}" method="post">
              @csrf
              @method('DELETE')
            </form>
            <button type="submit" form="destroy_photogallery_{{$gallery->id}}" title="Удалить" class="btn btn-sm btn-danger pull-right delete">
              <i class="voyager-trash"></i> <span class="hidden-xs hidden-sm">Удалить</span>
            </button>
            <a href="{{ route('admin.photogallery.edit', $gallery['id']) }}" title="Изменить" class="btn btn-sm btn-primary pull-right edit">
              <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Изменить</span>
            </a>
          </td>
        </tr>
        @empty
        @endforelse
        </tbody>
      </table>
      </div>
  </div>
@stop