routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('/');
Route::get('/', 'PageController@home')->name('home');

Route::name('pages.')->group(function () {

    Route::get('/actions', 'PageController@actions')->name('actions');
    Route::get('/photo-gallery', 'PageController@static')->name('gallery');
    Route::get('/contacts', 'PageController@contacts')->name('contacts');

    Route::get('/about', 'PageController@static')->name('about');
    Route::get('/services', 'PageController@static')->name('services');
    Route::get('/pay-delivery', 'PageController@static')->name('pay-delivery');

    Route::get('/page/{static}', 'PageController@static')->name('static');

    Route::get('/search', 'PageController@search')->name('search');
});

Route::prefix('/question')->name('question.')->group(function () {
    Route::get('/', 'QuestionController@show')->name('show');
    Route::post('/send', 'QuestionController@send')->name('send');
});

Route::name('articles.')->group(function () {
   Route::get('/articles', 'ArticleController@list')->name('list');
   Route::get('/articles/{article}', 'ArticleController@view')->name('view');
});

Route::name('catalog.')->prefix('/catalog')->group(function () {
    Route::get('/{categoriesURI}/product/{product}', 'ProductController@view')
        ->where('categoriesURI', '.+')->where('product', '.+')->name('product');

    Route::get('/{categoriesURI}/{category}', 'ProductCategoryController@subView')
        ->where(['categoriesURI' => '.+', 'category' => '.+'])->name('subcategory');
    Route::get('/{category}', 'ProductCategoryController@view')->where('category', '.+')
        ->name('category');
    Route::get('/', 'ProductCategoryController@catalog')->name('categories');
});

Route::get('/{any}', 'URLsController@index')->where('any', '^(?!admin|sitemap\.xml).*');
Route::get('/sitemap.xml', 'SitemapController@index');

Route::group(['prefix' => 'admin'], function () {
    Route::group(['prefix' => 'products', 'namespace' => 'Admin', 'middleware' => 'admin.user'], function () {
        Route::put('{id}/product-properties/update', 'ProductController@updateProperties')
            ->name('admin.products.product-properties.update');

        Route::get('properties', 'ProductPropertyController@index')->name('admin.products.properties');
        Route::post('properties/store', 'ProductPropertyController@store')->name('admin.products.property.store');
        Route::put('properties/update', 'ProductPropertyController@update')->name('admin.products.property.update');
        Route::delete('properties/delete', 'ProductPropertyController@delete')->name('admin.products.property.delete');

        Route::get('values/{property}', 'ProductPropertyCharController@index')->name('admin.products.property.value.char.names');
        Route::get('values', 'ProductPropertyCharController@all')->name('admin.products.property.value.char.all-names');
        Route::post('value/store', 'ProductPropertyCharController@store')->name('admin.products.property.value.char.name.store');
        Route::put('value/update', 'ProductPropertyCharController@update')->name('admin.products.property.value.char.name.update');
        Route::delete('value/delete', 'ProductPropertyCharController@delete')->name('admin.products.property.value.char.name.delete');
    });

    Route::group(['prefix' => 'categories', 'namespace' => 'Admin', 'middleware' => 'admin.user'], function () {
        Route::put('{id}/product-properties/update', 'ProductCategoryController@updateProductProperties')
            ->name('admin.categories.product-properties.update');
    });

    Voyager::routes();

    Route::resource('photogallery', 'Admin\PhotogalleryController', ['as' => 'admin', 'middleware' => 'admin.user']);
    Route::delete('photogallery/{photogallery}/{id}', 'Admin\PhotogalleryController@destroyItem')->name('admin.photogallery.item.delete');
});


resources/views/pages/actions.blade.php
@extends('layouts.main')

@section('structureData')
    {{ Breadcrumbs::view('breadcrumbs::json-ld', 'pages', $page, 'actions') }}
@endsection

@section('content')
    <section class="similar-section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    {{ Breadcrumbs::render('pages', $page, 'actions') }}
                </div>
            </div>

            <div class="row similar-goods">
                <h2 class="similar-goods__header">{{ $page->title ?? 'CПЕЦИАЛЬНЫЕ ПРЕДЛОЖЕНИЯ' }}</h2>

                @foreach($specialOffers as $product)
                <div class="col-xs-12 col-sm-12 col-lg-3 col-md-3 similar-goods__itemsimilar">

                    <figure class="similar-goods__item similar-goods__item_action">
                        <a href="{{ productPath($product) }}">
                            <img src="{{ asset('storage/' . $product->main_image) }}"
                                 class="img-responsive"
                                 alt="{{ $product->title }}"
                                 title="{{ $product->title }}">
                        </a>
                    </figure>

                    <h3 class="similar-goods__itemheader">
                        <a href="{{ productPath($product) }}">{{ $product->title }}</a>
                    </h3>
                    <a href="{{ productPath($product) }}" class="similar-goods__readmore">Посмотреть</a>
                </div>
                @endforeach

            </div>
        </div>

    </section>
@endsection

resources/views/pages/contacts.blade.php
@extends('layouts.main')

@section('header')
    <style>
        hr.contacts{
            margin-top: 40px;
            margin-bottom: 40px;
            border-top: 2px solid #f0f0f0;

        }
    </style>
@endsection

@section('structureData')
    {{ Breadcrumbs::view('breadcrumbs::json-ld', 'pages', $page, 'contacts') }}
@endsection

@section('content')
    <section class="similar-section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                {{ Breadcrumbs::render('pages', $page, 'contacts') }}
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <div class="contact-page">
                    <h1 class="contact-page__title">Контакты</h1>

                    <div class="contact-page__row">
                        <div class="contact-page__left">
                            {!! $page->description !!}
                        </div>
                        <div class="contact-page__right">
                            <img alt="" src="{{ asset('storage/templates/images/deliverys/b_1ea9c2f97cc8e213f9eaff88509a4e30_1334082873.jpg')}}">
                        </div>
                    </div>

{{--                    {DIVIRER}--}}
                </div>
            </div>
        </div>

        <div class="row maps">
            <div class="col-xs-12">
                <div class="mapwrap">
                    <div id="map"></div>
                </div>
            </div>
        </div>

    </div>
    </section>
@endsection

@section('scripts')
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAeMTmjNoQ_jfqGY7Mv9t8kt93MT_-7hTQ&callback=initMap"
            defer async></script>
    <script src="{{ asset('js/contacts.js') }}"></script>
@endsection

resources/views/pages/home.blade.php
@extends('layouts.main')

@section('content')
    <div class="bannersection">
        <div class="arrwrap">
            <div class="row">
                <!-- <a href="#" class="swiper-button-prev"></a>
                <a href="#" class="swiper-button-next"></a> -->
                <div class="swiper-container top_slider">
                    <div class="swiper-wrapper">
{{--                        <div class="swiper-slide top_greenslide">--}}
{{--                            <img alt="титульная" src="{{ asset('storage/templates/images/itypes/f6071bde5311b9be5032690792db5dd1_1526302130.jpg')}}" class="img-responsive" title="титульная">--}}
{{--                        </div>--}}
                        <div class="swiper-slide top_greenslide">
                            <iframe id="tour-3d" src="https://www.google.com/maps/embed?pb=!4v1581945017954!6m8!1m7!1sCAoSLEFGMVFpcE1keXludlJQSkRvWlA2dllCdWhiS3VURHd0b21LSHhFZDB6MUpi!2m2!1d47.8699615!2d35.0703103!3f235.64251368457346!4f-4.172796319706947!5f0.7820865974627469" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="similar-section">
        <div class="container">
            <div class="row similar-goods">
                <h2 class="similar-goods__header">Cпециальные предложения</h2>

                @foreach($specialOffers as $product)
                <div class="col-xs-12 col-sm-12 col-lg-3 col-md-3 similar-goods__itemsimilar">
                    <figure class="similar-goods__item similar-goods__item_action">
                        <a href="{{  productPath($product) }}">
                            <img alt="{{ $product->title }}"
                                 src="{{ asset('storage/' . $product->main_image) }}"
                                 class="img-responsive"
                                 title="{{ $product->title }}">
                        </a>
                    </figure>
                    <h3 class="similar-goods__itemheader"><a href="{{ productPath($product) }}">{{ $product->title }}</a></h3>
                    <a href="{{ productPath($product) }}" class="similar-goods__readmore">Посмотреть</a>
                </div>
                @endforeach

            </div>
        </div>
        <a href="{{ route('pages.actions') }}" class="seeall">Все предложения >></a>
    </section>

    <section class="aboutsection">
        <div class="container aboutsection-items">
            {!! $page->description !!}
        </div>
    </section>
@endsection

resources/views/pages/search.blade.php
@extends('layouts.main')

@section('structureData')
    {{ Breadcrumbs::view('breadcrumbs::json-ld', 'search') }}
@endsection

@section('content')
    <section class="similar-section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    {{ Breadcrumbs::render('search') }}
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12">
                    <div class="search-page">
                        <h2 class="search-page__title">Результаты поиска «{{ Request::get('word') }}»</h2>
                        <div class="search-page__content">
                            <div class="search-page__text"></div>
                            @if(!is_null($result))
                                @foreach($result as $item)
                                <div class="col-xs-12 col-sm-12 col-lg-3 col-md-3 similar-goods__itemsimilar">
                                    <figure class="similar-goods__item {{ $item->special_offer ? 'similar-goods__item_action' : '' }}">
                                        <a href="{{  productPath($item) }}">
                                            <img alt="{{ $item->title }}"
                                                src="{{ asset('storage/' . $item->main_image) }}"
                                                class="img-responsive"
                                                title="{{ $item->title }}">
                                        </a>
                                    </figure>
                                    <h3 class="similar-goods__itemheader"><a href="{{ productPath($item) }}">{{ $item->title }}</a></h3>
                                    <a href="{{ productPath($item) }}" class="similar-goods__readmore">Посмотреть</a>
                                </div>
                                @endforeach
                            @else
                                <div>По вашему запросу ничего не найдено</div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/static.blade.php
@extends('layouts.main')

@section('structureData')
    {{ Breadcrumbs::view('breadcrumbs::json-ld', 'pages', $page, $page->slug) }}
@endsection

@section('content')
    <section class="similar-section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                {{ Breadcrumbs::render('pages', $page, $page->slug) }}
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <div class="about-company">
                    <h1 class="about-company__title">{{ $page->title }}</h1>

                    <div class="about-company__text">{!! $page->description !!}</div>
                </div>
            </div>
        </div>
    </div>
    </section>
@endsection